[package]
name = "posh"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.12.3", features = ["derive"] }
crevice = "0.12.0"
mint = "0.5.9"
sealed = "0.4.0"
posh-derive = { path = "derive" }
glow = "0.11.2"

[workspace]
members = ["derive"]

[dev-dependencies]
sdl2 = "0.35.2"
