[package]
name = "posh"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
bytemuck = { version = "1.12.3", features = ["derive"] }
crevice = { version = "0.12.0", features = ["glam"] }
sealed = "0.4.0"
posh-derive = { path = "derive" }
glow = "0.11.2"
thiserror = "1.0.38"
glam = "0.22.0"
log = "0.4.17"

[workspace]
members = ["derive"]

[dev-dependencies]
glam = { version = "0.22.0" }
image = "0.24.5"
nanorand = "0.7.0"
sdl2 = "0.35.2"
simple_logger = "4.1.0"
