[package]
name = "posh"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
bytemuck = { version = "1.12.3", features = ["derive"] }
crevice = "0.12.0"
mint = "0.5.9"
sealed = "0.4.0"
posh-derive = { path = "derive" }
glow = "0.11.2"
thiserror = "1.0.38"

[workspace]
members = ["derive"]

[dev-dependencies]
glam = { version = "0.22.0", features = ["mint"] }
image = "0.24.5"
sdl2 = "0.35.2"
